server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://db-instance-hdshop.crzucsfqxps5.ap-northeast-1.rds.amazonaws.com:3306/hd-shop?useSSL=false
        username: admin
        password: jvVJ7j7k
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true

app:
    jwt-secret: 38a0963a6364b09ad867aa9a66c6d009673c21e182015461da236ec361877f77
    jwt-expiration-milliseconds: 604800000  # 1 week
