server:
    port: 8080
spring:
    datasource:
        password: 123hua@
        url: jdbc:mysql://localhost:3306/hd-shop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
    security:
        user:
            name: user
