server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://db-instance-hdshop.crzucsfqxps5.ap-northeast-1.rds.amazonaws.com:3306/hd-shop?useSSL=false
        username: admin
        password: jvVJ7j7k
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
