server:
    port: 5000

spring:
    datasource:
        url: jdbc:mysql://db-instance-hdshop.crzucsfqxps5.ap-northeast-1.rds.amazonaws.com:3306/hd-shop?useSSL=false
        username: admin
        password: jvVJ7j7k

