logging:
    level:
        org:
            springframework:
                security: debug

spring:
    application:
        name: hdshop
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                jdbc:
                    time_zone: Asia/Ho_Chi_Minh
        show-sql: true
    profiles:
        active: dev
    mail:
        default-encoding: UTF-8
        host: smtp.gmail.com
        port: 587
        username: huachhin@gmail.com
        password: sawm mnph hinp cqgy
        protocol: smtp
        properties:
            mail:
                debug: true
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    timeout: 25000
                    from: Duck Shop
                    starttls:
                        enable: true
    http:
        encoding:
            charset: UTF-8
    mvc:
        charset: UTF-8
    messages:
        basename: message
        encoding: UTF-8
        use-code-as-default-message: true
    web:
        locale: vi
        locale-resolver: fixed

app:
    jwt-secret: 38a0963a6364b09ad867aa9a66c6d009673c21e182015461da236ec361877f77
    jwt-expiration-milliseconds: 604800000 #1week
    cloudinary:
        cloud_name: dkurral2z
        api_key: 778991549327989
        api_secret: L9_wohW70nyFwZtEQu3GscjcouM
        folder_name: product_images_duck_shop

paging:
    default:
        page-number: 1
        page-size: 24

vnpay:
    tmn-code: ZCZAPALE
    hash-secret: EJWBFDLNDPPPGNODNZRFXZDEJPTAELNT
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
    return-url: /api/v1/vnpay/vnpay-payment






