logging:
  level:
    org:
      springframework:
        security: debug
spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: huachhin@gmail.com
    password: sawm mnph hinp cqgy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          from: Duck Shop




